# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8820fd24ebbf005758541d748dc42709e6769789bc5f32a5cacd993b2e84b27a28aff3eecafd016154bb7d88f3fa59632dc0bcf7558e08522d9474f8e465e82

test:
  secret_key_base: b2032193a5428788a2e2fbb6adb73424713fe5bb1c45cb29d4e995d07d7067adba39de4b75b24b68d70c388d8beda02babb6aff80b03ae12054f94bcb67509c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
